// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGL2NxNsZ0tve-4-1HXMswvVcCaVCa5Go',
    appId: '1:861420459575:web:0e0ca7f494b811153a91b2',
    messagingSenderId: '861420459575',
    projectId: 'recruiter-64a6b',
    authDomain: 'recruiter-64a6b.firebaseapp.com',
    storageBucket: 'recruiter-64a6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfaSvyn_vE7CyScZq5IplJt45Mclg0PmY',
    appId: '1:861420459575:android:748ae4a1e75291ec3a91b2',
    messagingSenderId: '861420459575',
    projectId: 'recruiter-64a6b',
    storageBucket: 'recruiter-64a6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgygDNOHpwYqOQ52wdIw1wuucLnTD5jFs',
    appId: '1:861420459575:ios:695cefcb6691374f3a91b2',
    messagingSenderId: '861420459575',
    projectId: 'recruiter-64a6b',
    storageBucket: 'recruiter-64a6b.appspot.com',
    iosBundleId: 'com.example.recruiter',
  );
}
